common:
  port: 80
  path: /root/example/static/
  base: https://example.com/
mysql:
  username: root
  password: password
  host: localhost
  port: 3306
  database: example
  charset: utf8
sqlite:
  path: /root/example.db
